In [1]:
!pip install numpy

'pip' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
import numpy as np

In [3]:
numpy_array = np.array([1,2,3,4])

In [4]:
numpy_array

array([1, 2, 3, 4])

In [5]:
type(numpy_array)

numpy.ndarray

In [6]:
twoD_array = np.array([[1,2,3,1],[2,5,3,2]])

In [7]:
twoD_array

array([[1, 2, 3, 1],
       [2, 5, 3, 2]])

In [8]:
threeD = np.array([[[2,2],[2,3]],[[3,3],[6,6]],[[4,4],[4,6]]])

In [9]:
threeD

array([[[2, 2],
        [2, 3]],

       [[3, 3],
        [6, 6]],

       [[4, 4],
        [4, 6]]])

In [10]:
np.array([1,2,3],dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [12]:
np.array([1,2,3], dtype=np.int64)

array([1, 2, 3])

In [14]:
np.array([0,3,4], dtype=bool)

array([False,  True,  True])

In [15]:
empty_list=[]
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [16]:
np.array(17)

array(17)

In [17]:
np.arange(17
          )

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [24]:
data=np.arange(1,17)
data.reshape(4,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [31]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [35]:
np.random.random((2,4))

array([[0.03448719, 0.24208306, 0.63935545, 0.64520339],
       [0.85673806, 0.69091569, 0.07262068, 0.63157691]])

In [36]:
#identify func

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
#Linespace

np.linspace(-10,10,3)

array([-10.,   0.,  10.])

In [38]:
arr = np.array([1,2,3])

In [39]:
arr

array([1, 2, 3])

In [40]:
arr.ndim

1

In [41]:
arr1=np.array([[[2,2],[2,2]],[[2,2],[2,2]],[[2,2],[2,2]]])

In [42]:
arr1

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [43]:
arr1.ndim

3

In [44]:
array1=np.array([[1,2,3],[1,2,3],[1,2,3]])

In [45]:
array1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [46]:
array1.shape

(3, 3)

In [47]:
array_elements=np.arange(3,3)

In [48]:
array_elements.size

0

In [49]:
np.array([[1,2],[3,4]]).dtype

dtype('int64')

In [50]:
import numpy as np

In [51]:
arr=np.arange(1,5).reshape(2,2)

In [52]:
arr

array([[1, 2],
       [3, 4]])

In [54]:
arr1.astype('float64')

array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]])

In [55]:
arr1.dtype

dtype('int64')

In [58]:
arr1=np.random.random((3,3))*100

In [59]:
arr1

array([[42.09044714, 30.90766973, 99.36533974],
       [50.15255242, 98.06223609, 30.98064035],
       [16.47681837, 12.3629712 , 51.00607061]])

In [60]:
round1=np.round(arr1)

In [61]:
arr1

array([[42.09044714, 30.90766973, 99.36533974],
       [50.15255242, 98.06223609, 30.98064035],
       [16.47681837, 12.3629712 , 51.00607061]])

In [62]:
round1

array([[42., 31., 99.],
       [50., 98., 31.],
       [16., 12., 51.]])

In [63]:
round1+2

array([[ 44.,  33., 101.],
       [ 52., 100.,  33.],
       [ 18.,  14.,  53.]])

In [64]:
round1-3

array([[39., 28., 96.],
       [47., 95., 28.],
       [13.,  9., 48.]])

In [66]:
arr1>300

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [67]:
arr_1= np.arange(1,17).reshape(4,4)

In [68]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [69]:
arr_2= np.arange(1,17).reshape(4,4)

In [70]:
arr_1 + arr_2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [71]:
np.max(arr_1)

np.int64(16)

In [73]:
arr_dara=np.round(np.random.random((4,4))*100).astype('int32')

In [74]:
arr_dara

array([[ 47,  42,   2, 100],
       [ 11,  69,  70,  58],
       [ 94,  67,   3,  39],
       [  8,  39,  64,  10]], dtype=int32)

In [75]:
np.max(arr_dara,axis=0)

array([ 94,  69,  70, 100], dtype=int32)

In [76]:
np.min(arr_dara,axis=1)

array([ 2, 11,  3,  8], dtype=int32)

In [77]:
arr=np.arange(1,10)

In [78]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.sin(60)

np.float64(-0.3048106211022167)

In [80]:
matrix1= np.round(np.random.random((3,3))*100).astype('int32')

In [82]:
matrix2= np.round(np.random.random((3,3))*100).astype('int32')

In [83]:
np.dot(matrix1,matrix2)

array([[ 5334,  9925,  9015],
       [ 4569,  4684,  3835],
       [ 7659, 10284,  9313]], dtype=int32)

In [84]:
np.log(matrix1)

array([[4.51085951, 3.04452244, 4.35670883],
       [2.19722458, 4.07753744, 1.60943791],
       [2.39789527, 4.48863637, 3.8501476 ]])

In [85]:
np.exp(matrix1)

array([[3.31740010e+39, 1.31881573e+09, 7.49841700e+33],
       [8.10308393e+03, 4.20121040e+25, 1.48413159e+02],
       [5.98741417e+04, 4.48961282e+38, 2.58131289e+20]])

In [86]:
np.round(matrix1)

array([[91, 21, 78],
       [ 9, 59,  5],
       [11, 89, 47]], dtype=int32)

In [87]:
np.ceil(matrix1)

array([[91, 21, 78],
       [ 9, 59,  5],
       [11, 89, 47]], dtype=int32)

In [88]:
np.floor(matrix1)

array([[91, 21, 78],
       [ 9, 59,  5],
       [11, 89, 47]], dtype=int32)

In [89]:
array = np.random.random((3,4))*10

In [90]:
array

array([[0.41006565, 1.40869172, 3.20512475, 8.77438714],
       [6.76679821, 0.29751966, 4.27142415, 9.60117275],
       [3.87389767, 6.18420011, 7.21260098, 4.81747517]])

In [91]:
np.round(array)

array([[ 0.,  1.,  3.,  9.],
       [ 7.,  0.,  4., 10.],
       [ 4.,  6.,  7.,  5.]])

In [92]:
trans=np.arange(1,5).reshape(2,2)

In [93]:
trans

array([[1, 2],
       [3, 4]])

In [95]:
trans.T

array([[1, 3],
       [2, 4]])

In [96]:
trans.T

array([[1, 3],
       [2, 4]])

In [97]:
np.transpose(trans)

array([[1, 3],
       [2, 4]])

In [98]:
np.ravel(trans)

array([1, 2, 3, 4])

In [99]:
np.ndim(trans)

2

In [100]:
aray=np.round(np.random.random((5,5))*100).astype('int32')

In [101]:
aray

array([[88, 96, 42, 27, 49],
       [17, 36, 64,  7, 22],
       [75, 87, 95,  3, 84],
       [75, 78, 59, 49, 26],
       [76, 96, 12, 60, 76]], dtype=int32)

In [102]:
aray[2,3]

np.int32(3)

In [103]:
aray3d=np.arange(1,9).reshape(2,2,2)

In [104]:
aray3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [105]:
aray

array([[88, 96, 42, 27, 49],
       [17, 36, 64,  7, 22],
       [75, 87, 95,  3, 84],
       [75, 78, 59, 49, 26],
       [76, 96, 12, 60, 76]], dtype=int32)

In [106]:
aray[:,3]

array([27,  7,  3, 49, 60], dtype=int32)

In [107]:
aray[0,:]

array([88, 96, 42, 27, 49], dtype=int32)