In [1]:
import numpy as np

In [2]:
array1=np.arange(1,11)

In [3]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array2=np.arange(4,13).reshape(3,3)

In [5]:
array2

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
array3=np.arange(10,61,10)

In [7]:
array3

array([10, 20, 30, 40, 50, 60])

In [8]:
array3.size

6

In [10]:
type(array3)

numpy.ndarray

In [12]:
array3.dtype

dtype('int64')

In [13]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])

In [14]:
A+B

array([11, 22, 33, 44])

In [15]:
A-B

array([ 9, 18, 27, 36])

In [16]:
A*B

array([ 10,  40,  90, 160])

In [17]:
A**B

array([     10,     400,   27000, 2560000])

In [18]:
np.add(A,B)

array([11, 22, 33, 44])

In [19]:
np.subtract(A,B)

array([ 9, 18, 27, 36])

In [21]:
values=np.array([2,3,4,5])

In [22]:
np.sqrt(values)

array([1.41421356, 1.73205081, 2.        , 2.23606798])

In [23]:
np.exp(values)

array([  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ])

In [24]:
np.log(values)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [25]:
np.sum(values)

np.int64(14)

In [26]:
values

array([2, 3, 4, 5])

In [27]:
np.cumsum(values)

array([ 2,  5,  9, 14])

In [28]:
data=np.arange(10,91,10).reshape(3,3)

In [29]:
data

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [30]:
np.sum(data,axis=0)

array([120, 150, 180])

In [31]:
np.sum(data, axis=1)

array([ 60, 150, 240])

In [32]:
np.min(data)

np.int64(10)

In [33]:
np.max(data)

np.int64(90)

In [34]:
np.mean(data)

np.float64(50.0)

In [35]:
mark = np.array([23,56,4,8,33,22,6,77,98])

In [36]:
np.mean(mark)

np.float64(36.333333333333336)

In [37]:
np.median(mark)

np.float64(23.0)

In [38]:
np.var(mark)

np.float64(1000.6666666666666)

In [39]:
np.std(mark)

np.float64(31.63331577098213)

In [41]:
max1=np.max(mark)

In [42]:
max1

np.int64(98)

In [44]:
sales = np.array([1200,1500,900,2000,1800,1700,1600])
days = np.array(["sun","mon","tue","wed","thur","fri","sat"])

In [45]:
for i in sales:
    weekly = i*7

In [46]:
weekly

np.int64(11200)

In [47]:
avg=np.sum(sales)/7

In [48]:
avg

np.float64(1528.5714285714287)

In [49]:
highest=np.max(sales)

In [50]:
highest

np.int64(2000)

In [51]:
lowest=np.min(sales)

In [52]:
lowest

np.int64(900)

In [53]:
sales

array([1200, 1500,  900, 2000, 1800, 1700, 1600])

In [54]:
sd=np.std(sales)

In [55]:
sd

np.float64(345.2298849598449)

In [56]:
for i in sales:
    if i > avg:
        print(i)

2000
1800
1700
1600
